name: flutter_blue
publish_to: none
description: Bluetooth plugin for Flutter
version: 0.1.0

homepage: https://github.com/truongsinh/flutter_bluetooth

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  convert: "^3.0.0"
  protobuf: "^2.0.1"
  uuid_enhanced:
    git:
      url: https://github.com/marciovalim/dart-uuid.git
      ref: master
  collection: ^1.14.11
  meta: ^1.1.6

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dev_dependencies:
  pedantic: ^1.5.0
  flutter_test:
    sdk: flutter
